openapi: "3.0.0"
info:
  title: "Example API"
  version: "1.0.0"
paths:
  /example:
    post:
      summary: "Example POST endpoint"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
